[[edge_functions]]
  path = "/colaborador/financeiro_novo*"
  function = "protect-finance"
[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.googleapis.com https://www.googletagmanager.com https://www.google-analytics.com https://accounts.google.com;
  connect-src 'self' https://*.firebaseio.com https://www.googleapis.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com wss://*.firebaseio.com;
  img-src 'self' data: https:;
  style-src 'self' 'unsafe-inline';
  font-src 'self' data: https:;
  frame-src https://*.firebaseapp.com https://accounts.google.com https://*.google.com;
  """
  X-Content-Type-Options = "nosniff"
